/**
 * CIVIC PULSE — Contract Parity Mock Data
 * Strictly compliant with DATA_CONTRACT.md and API_CONTRACT.md.
 * Represents Pune Municipal Corporation (PMC) infrastructure intelligence.
 */

import type {
  SystemStatus,
  Complaint,
  FailureCluster,
  Case,
  Evidence,
  SatelliteObservation,
  Intervention,
  CounterfactualScenario,
  DecisionBrief,
  WorkOrder,
  VerificationRecord,
  Outcome,
  InfrastructureMemory,
  CrossCityCase,
  IntakeJobStatus,
  OperationalConstraints,
} from '@/types';

// ─── 1. System Status ───────────────────────────────────────────────────────

export const mockSystemStatus: SystemStatus = {
  system: 'OPERATIONAL',
  region: 'Pune Municipal Corporation (PMC)',
  data_mode: 'DEMO DATA',
  complaints_processed: 1248,
  failure_clusters: 186,
  recurring_failures: 42,
  high_impact_failures: 17,
  unresolved_recurring: 9,
  completed_interventions: 31,
  recurrence_cases: 12,
};

// ─── 2. Normalized Complaints ───────────────────────────────────────────────

export const mockComplaints: Complaint[] = [
  {
    complaint_id: 'CMP-2026-0101',
    title: 'Severe roadway submergence at Goodluck Chowk',
    description: 'Rainwater depth exceeding 45cm preventing vehicular movement outside Cafe Goodluck. Roadside curb inlets backflowing.',
    incident_type: 'WATERLOGGING',
    reported_at: '2026-10-02T14:15:00Z',
    site_id: 'SITE-PUN-001',
    cluster_id: 'CLU-PUN-001',
    severity: 'CRITICAL',
    source: 'PMC Citizen Portal (Pune Connect)',
    data_truth: 'REAL_DATA',
    latitude: 18.5186,
    longitude: 73.8415,
    address: 'Goodluck Chowk, FC Road, Shivajinagar, Pune',
  },
  {
    complaint_id: 'CMP-2026-0102',
    title: 'Fergusson College Main Gate junction flooded',
    description: 'Pedestrian sidewalk and road submerged in 30cm dirty runoff. Silt accumulation visible over drainage grates.',
    incident_type: 'WATERLOGGING',
    reported_at: '2026-10-02T14:28:00Z',
    site_id: 'SITE-PUN-001',
    cluster_id: 'CLU-PUN-001',
    severity: 'HIGH',
    source: 'PMC Helpline 1800-1030-222',
    data_truth: 'REAL_DATA',
    latitude: 18.5212,
    longitude: 73.8423,
    address: 'FC Road outside Main Campus Gate, Shivajinagar, Pune',
  },
  {
    complaint_id: 'CMP-2026-0103',
    title: 'Stormwater drain backflow onto Hong Kong Lane',
    description: 'Manhole cover displaced by water pressure; foul stormwater flooding shopping stalls and blocking emergency passage.',
    incident_type: 'DRAINAGE_OVERFLOW',
    reported_at: '2026-10-02T14:40:00Z',
    site_id: 'SITE-PUN-001',
    cluster_id: 'CLU-PUN-001',
    severity: 'CRITICAL',
    source: 'Twitter / X (@PuneTrafficAlert)',
    data_truth: 'REAL_DATA',
    latitude: 18.5198,
    longitude: 73.8419,
    address: 'Hong Kong Lane, off FC Road, Pune',
  },
  {
    complaint_id: 'CMP-2026-0104',
    title: 'Traffic stagnation near Deccan Gymkhana Bus Stop',
    description: 'Two-wheelers stalling in waist-level water accumulation near Sambhaji Park subway entrance.',
    incident_type: 'TRAFFIC_HALT',
    reported_at: '2026-10-02T15:02:00Z',
    site_id: 'SITE-PUN-001',
    cluster_id: 'CLU-PUN-001',
    severity: 'HIGH',
    source: 'Pune Traffic Police Control Dispatch',
    data_truth: 'REAL_DATA',
    latitude: 18.5171,
    longitude: 73.8409,
    address: 'J.M. Road - Deccan Gymkhana Bus Stand, Pune',
  },
  {
    complaint_id: 'CMP-2026-0105',
    title: 'Clogged roadside chamber opposite Vaishali Restaurant',
    description: 'Plastics and construction debris blocking drop inlet chamber. Storm runoff diverting into dining area.',
    incident_type: 'CHAMBER_BLOCKAGE',
    reported_at: '2026-10-02T15:18:00Z',
    site_id: 'SITE-PUN-001',
    cluster_id: 'CLU-PUN-001',
    severity: 'MODERATE',
    source: 'PMC Citizen Portal',
    data_truth: 'REAL_DATA',
    latitude: 18.5192,
    longitude: 73.8417,
    address: 'FC Road opposite Hotel Vaishali, Shivajinagar',
  },
  {
    complaint_id: 'CMP-2026-0106',
    title: 'Karve Road Paud Phata underpass submerged',
    description: 'Vehicle trapped in underpass puddle depth 60cm. Automatic pumping system offline.',
    incident_type: 'UNDERPASS_SUBMERGENCE',
    reported_at: '2026-10-02T15:35:00Z',
    site_id: 'SITE-PUN-002',
    cluster_id: 'CLU-PUN-002',
    severity: 'CRITICAL',
    source: 'PMC Emergency Operations Center',
    data_truth: 'REAL_DATA',
    latitude: 18.5082,
    longitude: 73.8291,
    address: 'Paud Phata Flyover Underpass, Karve Road, Pune',
  },
  {
    complaint_id: 'CMP-2026-0107',
    title: 'Sinhagad Road Rajaram Bridge chronic water pooling',
    description: 'Riverbank storm outlet submerged under Mutha River swell causing backward stormwater head pressure.',
    incident_type: 'RIVER_OUTFALL_HEADBACK',
    reported_at: '2026-10-02T15:50:00Z',
    site_id: 'SITE-PUN-003',
    cluster_id: 'CLU-PUN-003',
    severity: 'HIGH',
    source: 'Irrigation Department Liaison Officer',
    data_truth: 'REAL_DATA',
    latitude: 18.4912,
    longitude: 73.8267,
    address: 'Sinhagad Road near Rajaram Bridge, Hingne Khurd, Pune',
  },
  {
    complaint_id: 'CMP-2026-0108',
    title: 'Balgandharva Chowk JM Road left lane waterlogging',
    description: 'Sheet runoff collecting along curb; storm drain line full with silt deposit.',
    incident_type: 'WATERLOGGING',
    reported_at: '2026-10-02T16:05:00Z',
    site_id: 'SITE-PUN-004',
    cluster_id: 'CLU-PUN-004',
    severity: 'MODERATE',
    source: 'Ward Inspector Field Inspection',
    data_truth: 'REAL_DATA',
    latitude: 18.5225,
    longitude: 73.8488,
    address: 'Balgandharva Ranga Mandir Chowk, J.M. Road, Pune',
  },
];

// ─── 3. Failure Clusters ────────────────────────────────────────────────────

export const mockClusters: FailureCluster[] = [
  {
    cluster_id: 'CLU-PUN-001',
    case_id: 'CAS-PUN-2026-001',
    title: 'FC Road Corridor Recurring Waterlogging',
    complaint_count: 18,
    incident_count: 4,
    confidence: 0.86,
    site_id: 'SITE-PUN-001',
    status: 'INVESTIGATING',
    location_name: 'FC Road - Goodluck Chowk to Fergusson Gate',
    failure_type: 'Drainage constraint + terrain accumulation',
    grouping_explanation: '18 citizen & sensor complaints concentrated within 150m radius of Goodluck depression during intensity peak (>30mm/hr runoff surge).',
    recurrence_level: 'HIGH',
    is_high_impact: true,
    is_recurring: true,
    latitude: 18.5186,
    longitude: 73.8415,
    member_complaint_ids: [
      'CMP-2026-0101',
      'CMP-2026-0102',
      'CMP-2026-0103',
      'CMP-2026-0104',
      'CMP-2026-0105',
    ],
  },
  {
    cluster_id: 'CLU-PUN-002',
    case_id: 'CAS-PUN-2026-002',
    title: 'Karve Road Paud Phata Sump & Underpass Failure',
    complaint_count: 12,
    incident_count: 3,
    confidence: 0.82,
    site_id: 'SITE-PUN-002',
    status: 'ACTIVE',
    location_name: 'Karve Road Paud Phata Underpass',
    failure_type: 'Pump electrical tripped + drainage inlet debris',
    grouping_explanation: 'Underpass sump gravity drainage exceeded with dual submersible pump electrical trip.',
    recurrence_level: 'HIGH',
    is_high_impact: true,
    is_recurring: true,
    latitude: 18.5082,
    longitude: 73.8291,
    member_complaint_ids: ['CMP-2026-0106'],
  },
  {
    cluster_id: 'CLU-PUN-003',
    case_id: 'CAS-PUN-2026-003',
    title: 'Sinhagad Road Mutha Outfall Head Pressure Stagnation',
    complaint_count: 9,
    incident_count: 2,
    confidence: 0.79,
    site_id: 'SITE-PUN-003',
    status: 'ACTIVE',
    location_name: 'Sinhagad Road Rajaram Bridge Outfall',
    failure_type: 'River level backflow into roadside trunk',
    grouping_explanation: 'High Khadakwasla dam discharge river level exceeds trunk invert elevation; missing flap valve.',
    recurrence_level: 'MEDIUM',
    is_high_impact: false,
    is_recurring: true,
    latitude: 18.4912,
    longitude: 73.8267,
    member_complaint_ids: ['CMP-2026-0107'],
  },
  {
    cluster_id: 'CLU-PUN-004',
    case_id: 'CAS-PUN-2026-004',
    title: 'JM Road Balgandharva Curb Ponding',
    complaint_count: 7,
    incident_count: 2,
    confidence: 0.74,
    site_id: 'SITE-PUN-004',
    status: 'RESOLVED',
    location_name: 'JM Road Balgandharva Chowk',
    failure_type: 'Surface grate leaf litter & silt blockage',
    grouping_explanation: 'Curb grating covered by fallen foliage during storm onset.',
    recurrence_level: 'LOW',
    is_high_impact: false,
    is_recurring: false,
    latitude: 18.5225,
    longitude: 73.8488,
    member_complaint_ids: ['CMP-2026-0108'],
  },
];

// ─── 4. Detailed Case (CAS-PUN-2026-001) ────────────────────────────────────

export const mockDetailedCase: Case = {
  case_id: 'CAS-PUN-2026-001',
  cluster_id: 'CLU-PUN-001',
  site_id: 'SITE-PUN-001',
  title: 'Recurring Waterlogging — FC Road Corridor',
  failure_type: 'Drainage constraint + terrain accumulation',
  status: 'INVESTIGATING',
  created_at: '2026-10-02T16:00:00Z',
  fingerprint: {
    summary: 'RECURRING WATERLOGGING',
    complaint_count: 18,
    incident_count: 4,
    confidence: 0.86,
    primary_cause: 'Drainage constraint + terrain accumulation',
    rainfall_threshold_mm: 28.5,
    catchment_slope_pct: 2.4,
    drain_capacity_deficit_pct: 42.0,
    data_truth: 'MODEL_ESTIMATION',
  },
  hypotheses: [
    {
      hypothesis_id: 'HYP-001',
      case_id: 'CAS-PUN-2026-001',
      title: 'Drainage capacity & silt bottleneck in 600mm conduit',
      confidence: 0.86,
      status: 'CONFIRMED',
      evidence_ids: ['EV-001', 'EV-002', 'EV-004'],
    },
    {
      hypothesis_id: 'HYP-002',
      case_id: 'CAS-PUN-2026-001',
      title: 'Micro-basin terrain depression accumulating hillside runoff',
      confidence: 0.79,
      status: 'SUPPORTED',
      evidence_ids: ['EV-003', 'EV-005'],
    },
    {
      hypothesis_id: 'HYP-003',
      case_id: 'CAS-PUN-2026-001',
      title: 'Surface drop inlet density insufficient for peak runoff intensity',
      confidence: 0.73,
      status: 'SUPPORTED',
      evidence_ids: ['EV-006', 'EV-008'],
    },
  ],
  failure_chain: {
    nodes: [
      {
        id: 'fc-1',
        label: 'Heavy Rainfall (>30mm/hr)',
        type: 'trigger',
        evidence_ids: ['EV-001'],
        status: 'confirmed',
        description: 'Precipitation exceeded local soil absorption rate, recorded by IMD Shivaji Nagar station.',
      },
      {
        id: 'fc-2',
        label: 'High Surface Runoff',
        type: 'hydrology',
        evidence_ids: ['EV-002'],
        status: 'confirmed',
        description: 'Impervious paved surfaces across Ferguson Hill apron accelerated 88% overland runoff volume.',
      },
      {
        id: 'fc-3',
        label: 'Terrain Depression (Goodluck Basin)',
        type: 'terrain',
        evidence_ids: ['EV-003'],
        status: 'confirmed',
        description: 'Natural 1.2m localized elevation bowl traps water at the Goodluck junction.',
      },
      {
        id: 'fc-4',
        label: 'Drainage Bottleneck (600mm Pipe Silted)',
        type: 'infrastructure',
        evidence_ids: ['EV-004'],
        status: 'confirmed',
        description: 'CCTV Sonde revealed 45% cross-section silt accumulation severely capping gravity discharge.',
      },
      {
        id: 'fc-5',
        label: 'Water Accumulation (45cm Depth)',
        type: 'hazard',
        evidence_ids: ['EV-005'],
        status: 'confirmed',
        description: 'Sentinel-1 SAR and traffic video confirmed 180m continuous standing pool lasting >2.5 hours.',
      },
      {
        id: 'fc-6',
        label: 'Road Disruption & Traffic Paralysis',
        type: 'impact',
        evidence_ids: ['EV-006'],
        status: 'confirmed',
        description: 'Major arterial shutdown on FC Road cascading severe traffic delays across Deccan Gymkhana.',
      },
      {
        id: 'fc-7',
        label: '18 Citizen Complaints',
        type: 'symptom',
        evidence_ids: ['EV-007'],
        status: 'confirmed',
        description: 'Rapid influx of grievances logged via Pune Connect portal and traffic police alerts.',
      },
    ],
    edges: [
      { source: 'fc-1', target: 'fc-2', relationship: 'generates' },
      { source: 'fc-2', target: 'fc-3', relationship: 'flows_into' },
      { source: 'fc-3', target: 'fc-4', relationship: 'overwhelms' },
      { source: 'fc-4', target: 'fc-5', relationship: 'causes' },
      { source: 'fc-5', target: 'fc-6', relationship: 'results_in' },
      { source: 'fc-6', target: 'fc-7', relationship: 'triggers' },
    ],
  },
  history: [
    {
      year: '2024',
      date: '2024-07-15',
      event: 'Citizen complaint: 35cm waterlogging during monsoon downpour',
      type: 'COMPLAINT',
      evidence_id: 'EV-H01',
      notes: 'Initial localized complaint logged at Goodluck Chowk.',
    },
    {
      year: '2025',
      date: '2025-05-20',
      event: 'Pre-monsoon drain cleaning executed by ward contractor (Manual silt clearance)',
      type: 'INTERVENTION',
      evidence_id: 'EV-H02',
      notes: 'Manual clearing of surface drop chambers without mechanical pipe desilting.',
    },
    {
      year: '2025',
      date: '2025-08-11',
      event: 'Recurrence observed after 3 months (40mm downpour re-submerged junction)',
      type: 'RECURRENCE',
      evidence_id: 'EV-H03',
      notes: 'Demonstrated limited durability of superficial manual desilting.',
    },
    {
      year: '2026',
      date: '2026-10-02',
      event: '18 complaints logged in 3 hours during monsoon surge',
      type: 'COMPLAINT',
      evidence_id: 'EV-H04',
      notes: 'Triggered automated failure clustering and cluster promotion.',
    },
    {
      year: '2026',
      date: '2026-10-04',
      event: 'Civic Pulse Multi-Evidence Investigation Case opened',
      type: 'INVESTIGATION',
      evidence_id: 'EV-H05',
      notes: 'Comprehensive sensor, satellite, and hydraulic screening initialized.',
    },
  ],
  decision_readiness: {
    ready: true,
    evidence_sufficiency: 0.88,
    stakeholder_signoff_required: true,
    recommended_action: 'Proceed to Intervention Lab & Work Order Authorization',
  },
};

// ─── 5. Evidence Ledger ─────────────────────────────────────────────────────

export const mockEvidenceList: Evidence[] = [
  {
    evidence_id: 'EV-001',
    case_id: 'CAS-PUN-2026-001',
    type: 'RAINFALL',
    title: 'IMD Pune Shivaji Nagar Station Precipitation Telemetry',
    source: 'IMD Automated Weather Station #43122',
    confidence: 0.96,
    data_truth: 'REAL_DATA',
    value: '48.2 mm in 120 minutes (Peak intensity 32.4 mm/hr)',
    unit: 'mm/hr',
    observed_at: '2026-10-02T15:30:00Z',
    description: 'Precipitation exceeded the 5-year return period threshold for urban drainage design in Ward 14.',
  },
  {
    evidence_id: 'EV-002',
    case_id: 'CAS-PUN-2026-001',
    type: 'ROAD',
    title: 'Smart City Surface CCTV Optical Runoff Velocity',
    source: 'Pune Smart City Command CCTV Camera #FC-08',
    confidence: 0.91,
    data_truth: 'REAL_DATA',
    value: '1.85 m/s overland sheet velocity along curb',
    unit: 'm/s',
    observed_at: '2026-10-02T14:45:00Z',
    description: 'Computer vision vehicle splash and curb flow tracking calculated rapid sheet velocity bypassing choked grates.',
  },
  {
    evidence_id: 'EV-003',
    case_id: 'CAS-PUN-2026-001',
    type: 'TERRAIN',
    title: 'CartoDEM 10m Hydrologic Flow Accumulation & Slope Basin',
    source: 'ISRO Bhuvan CartoDEM Elevation Model',
    confidence: 0.85,
    data_truth: 'MODEL_ESTIMATION',
    value: 'Localized basin depression depth 1.18m with 2.4% slope convergence',
    unit: 'm',
    observed_at: '2026-10-03T09:00:00Z',
    description: 'Screening-level DEM shows FC Road acts as a secondary conveyance channel for the western Fergusson hill catchment.',
  },
  {
    evidence_id: 'EV-004',
    case_id: 'CAS-PUN-2026-001',
    type: 'DRAINAGE',
    title: 'CCTV Stormwater Conduit Sonde Internal Cross-Section',
    source: 'PMC Drainage Department Robotic Inspection Rover',
    confidence: 0.94,
    data_truth: 'REAL_DATA',
    value: '45% cross-sectional silt & construction sediment deposit',
    unit: '%',
    observed_at: '2026-10-03T11:00:00Z',
    description: 'Robotic inspection inside 600mm concrete pipe confirmed heavy compacted silt over 120m stretch between Goodluck and FC Gate.',
  },
  {
    evidence_id: 'EV-005',
    case_id: 'CAS-PUN-2026-001',
    type: 'SATELLITE',
    title: 'Sentinel-1 SAR Surface Backscatter Standing Water Anomaly',
    source: 'ESA Copernicus Sentinel-1 GRD (VV/VH Polarimetry)',
    confidence: 0.82,
    data_truth: 'EVIDENCE',
    value: 'Surface dielectric drop -3.8 dB consistent with specular water reflection',
    unit: 'dB',
    observed_at: '2026-10-02T18:24:00Z',
    description: 'Independent spatial evidence: Synthetic Aperture Radar detects specular backscatter drop matching 180m continuous flooded corridor.',
  },
  {
    evidence_id: 'EV-006',
    case_id: 'CAS-PUN-2026-001',
    type: 'ROAD',
    title: 'Google Mobility API Traffic Congestion Index Spike',
    source: 'Pune Traffic Police ITS Traffic Sensor System',
    confidence: 0.95,
    data_truth: 'REAL_DATA',
    value: 'Speed drop from 28 km/h to 3.2 km/h (88% reduction)',
    unit: 'km/h',
    observed_at: '2026-10-02T15:00:00Z',
    description: 'Traffic congestion cascaded across JM Road, Karve Road, and Law College Road networks.',
  },
  {
    evidence_id: 'EV-007',
    case_id: 'CAS-PUN-2026-001',
    type: 'COMPLAINT',
    title: '18 Geo-Verified Citizen Complaints Docket Batch',
    source: 'PMC Citizen Grievance Redressal Cell',
    confidence: 0.98,
    data_truth: 'REAL_DATA',
    value: '18 verified citizen tickets with geo-tagged images',
    unit: 'tickets',
    observed_at: '2026-10-02T16:00:00Z',
    description: 'All 18 reports clustered within 150m radius of Goodluck Chowk; verified valid coordinates.',
  },
  {
    evidence_id: 'EV-008',
    case_id: 'CAS-PUN-2026-001',
    type: 'DRAINAGE',
    title: 'Screening-Level Hydraulic Capacity / Exceedance Ratio',
    source: 'Rational Method Hydrologic Screening Model (PMC Standard)',
    confidence: 0.84,
    data_truth: 'MODEL_ESTIMATION',
    value: 'Capacity/Demand Ratio = 0.58 (42% Capacity Deficit)',
    unit: 'ratio',
    observed_at: '2026-10-03T12:00:00Z',
    description: 'Screening-level estimate. Assumes catchment area 14.2 ha, runoff coefficient C=0.75, pipe Manning n=0.015.',
  },
];

// ─── 6. Satellite / Earth Observation ───────────────────────────────────────

export const mockSatelliteObservation: SatelliteObservation = {
  observation_id: 'SAT-PUN-2026-001',
  case_id: 'CAS-PUN-2026-001',
  satellite: 'Sentinel-1 SAR',
  acquisition_date: '2026-10-02T18:24:12Z',
  label: 'INDEPENDENT SPATIAL EVIDENCE',
  metric_name: 'Radar Backscatter VV Delta',
  metric_value: '-3.8 dB (Wet Surface Specular Reflection)',
  supporting_confidence: 0.82,
  data_truth: 'EVIDENCE',
  description: 'Independent spatial evidence indicates significant dielectric surface change along FC Road corridor between Goodluck Chowk and Fergusson College Gate. Radar backscatter characteristic matches water pooling depth >10cm over impervious asphalt.',
  imagery_url: '/images/satellite_waterlogging_fc_road.jpg',
  baseline_imagery_url: '/images/satellite_dry_baseline_fc_road.jpg',
  comparison_notes: 'Compared against dry-season baseline acquired 2026-09-18. Spatial alignment confirmed with zero geometric offset along road centerline.',
};

// ─── 7. Intervention Lab ────────────────────────────────────────────────────

export const mockInterventions: Intervention[] = [
  {
    intervention_id: 'INT-001',
    case_id: 'CAS-PUN-2026-001',
    title: 'Mechanized High-Pressure Desilting & Catch-Pit Clearing',
    description: 'Deploy vacuum suction tanker + high-pressure water jetting unit to clear 45% conduit silt deposition across 120m stretch from Goodluck Chowk to Fergusson Gate.',
    ranking_tier: 'RECOMMENDED',
    estimated_cost: 85000,
    estimated_duration_days: 3,
    workers_required: 6,
    overall_score: 0.84,
    scores: {
      impact_score: 0.82,
      budget_fit: 0.95,
      deadline_fit: 0.94,
      evidence_confidence: 0.86,
      recurrence_reduction: 0.68,
      overall_score: 0.84,
    },
    equipment: ['vacuum_suction_tanker', 'high_pressure_jetting_unit', 'traffic_safety_cordon'],
    materials: ['manhole_safety_mesh', 'sludge_containment_sacks'],
    complaints_addressed: 18,
    expected_risk_reduction: 0.68,
    recurrence_outlook: 'Moderate (6–9 months before gradual re-sedimentation)',
    maintenance_burden: 'Quarterly pre-monsoon mechanical jetting recommended',
    future_savings: 240000,
    budget_fit: 0.95,
    deadline_fit: 0.94,
  },
  {
    intervention_id: 'INT-002',
    case_id: 'CAS-PUN-2026-001',
    title: 'Precast Drop-Inlet Installation + Camber Regrading',
    description: 'Install 2 supplemental curb-cut cast-iron grating drop-inlets and re-grade 40m asphalt lip to divert micro-basin ponding into secondary stormwater trunk.',
    ranking_tier: 'ALTERNATIVE',
    estimated_cost: 142000,
    estimated_duration_days: 7,
    workers_required: 8,
    overall_score: 0.81,
    scores: {
      impact_score: 0.89,
      budget_fit: 0.82,
      deadline_fit: 0.78,
      evidence_confidence: 0.84,
      recurrence_reduction: 0.84,
      overall_score: 0.81,
    },
    equipment: ['mini_excavator', 'asphalt_roller', 'concrete_saw_cutter'],
    materials: ['precast_concrete_drop_chambers', 'heavy_duty_cast_iron_gratings', 'cold_mix_asphalt'],
    complaints_addressed: 18,
    expected_risk_reduction: 0.84,
    recurrence_outlook: 'High durability (>36 months minimal ponding)',
    maintenance_burden: 'Low (annual pre-monsoon chamber silt clearance)',
    future_savings: 520000,
    budget_fit: 0.82,
    deadline_fit: 0.78,
  },
  {
    intervention_id: 'INT-003',
    case_id: 'CAS-PUN-2026-001',
    title: 'Stormwater Conduit Upsizing (600mm → 900mm R.C.C. Pipe)',
    description: 'Longitudinal trench excavation and pipe upsizing from Goodluck Chowk to Mutha River outfall with reinforced catch-pits.',
    ranking_tier: 'HIGH_IMPACT',
    estimated_cost: 480000,
    estimated_duration_days: 21,
    workers_required: 14,
    overall_score: 0.65,
    scores: {
      impact_score: 0.96,
      budget_fit: 0.32,
      deadline_fit: 0.40,
      evidence_confidence: 0.88,
      recurrence_reduction: 0.94,
      overall_score: 0.65,
    },
    equipment: ['hydraulic_breaker', 'crane_truck', 'heavy_excavator', 'compactor'],
    materials: ['900mm_rcc_np3_pipes', 'reinforced_bedding_concrete', 'chamber_covers'],
    complaints_addressed: 18,
    expected_risk_reduction: 0.94,
    recurrence_outlook: 'Permanent structural resolution (>10 years durability)',
    maintenance_burden: 'Standard bi-annual municipal inspection',
    future_savings: 1200000,
    budget_fit: 0.32,
    deadline_fit: 0.40,
  },
];

// ─── 8. Counterfactual Scenarios ────────────────────────────────────────────

export const mockCounterfactual: CounterfactualScenario[] = [
  {
    id: 'CF-0',
    name: 'DO NOTHING (Status Quo)',
    expected_recurrence: '88% probability at next rainfall >25mm/hr',
    estimated_cost: 0,
    duration_days: 0,
    impact_summary: 'Severe ongoing flood risk; persistent transit halts; shopfront flooding',
    exposure_summary: '₹4.8 Lakh projected municipal & commercial disruption per monsoon spell',
    future_savings: 0,
    assumptions: [
      'Rainfall patterns consistent with 2024-2026 monsoon baseline',
      'Existing 45% silt block will continue to compact and solidify',
      'Traffic delay cost estimated at ₹500/vehicle/hour disruption',
    ],
    is_status_quo: true,
    score: 0.12,
  },
  {
    id: 'CF-1',
    name: 'OPTION A: Mechanized Desilting (INT-001)',
    expected_recurrence: '32% probability (effective for 6-9 months)',
    estimated_cost: 85000,
    duration_days: 3,
    impact_summary: 'Immediate flow restoration; 68% risk reduction within 72 hours',
    exposure_summary: '₹1.1 Lakh residual exposure (re-sedimentation risk without regrading)',
    future_savings: 240000,
    assumptions: [
      'High-pressure jetting can dislodge compacted silt without pipe wall cracking',
      'Silt containment disposed at designated PMC landfill',
    ],
    score: 0.84,
  },
  {
    id: 'CF-2',
    name: 'OPTION B: Drop-Inlet + Regrading (INT-002)',
    expected_recurrence: '16% probability (high durability >36 months)',
    estimated_cost: 142000,
    duration_days: 7,
    impact_summary: 'Eliminates localized elevation trap; 84% long-term risk reduction',
    exposure_summary: '₹45,000 minor residual risk during extreme cloudburst (>60mm/hr)',
    future_savings: 520000,
    assumptions: [
      'Night-time lane closures permitted by Pune Traffic Police',
      'Secondary stormwater line has spare conveyance capacity',
    ],
    score: 0.81,
  },
  {
    id: 'CF-3',
    name: 'OPTION C: Conduit Upsizing (INT-003)',
    expected_recurrence: '6% probability (structural permanent upgrade)',
    estimated_cost: 480000,
    duration_days: 21,
    impact_summary: '94% risk reduction; withstands 50-year rainfall storms',
    exposure_summary: '₹0 residual risk under normal operating conditions',
    future_savings: 1200000,
    assumptions: [
      'Budget allocation authorized under PMC Major Capital Works budget',
      '21-day full arterial traffic diversion plan approved',
    ],
    score: 0.65,
  },
];

// ─── 9. Decision Brief ──────────────────────────────────────────────────────

export const mockDecisionBrief: DecisionBrief = {
  case_id: 'CAS-PUN-2026-001',
  problem: 'Recurring urban waterlogging at Goodluck Chowk along FC Road corridor, causing 45cm flooding, 18 citizen complaints, and traffic paralysis across Shivajinagar.',
  why_it_happened: 'Micro-basin terrain depression (1.18m elevation bowl) concentrates stormwater runoff from the western hill slope into a 600mm conduit that is 45% choked with silt and debris.',
  evidence_summary: [
    'IMD Station #43122 recorded 48.2mm intense downpour exceeding local drainage threshold',
    'Robotic CCTV Sonde confirmed 45% compacted sediment restricting hydraulic cross-section',
    'Sentinel-1 SAR radar backscatter detected continuous -3.8dB surface water anomaly',
    'Rational method hydraulic screening indicates 42% capacity deficit under peak conditions',
  ],
  history_summary: 'Location experienced waterlogging in 2024 and 2025. Superficial manual cleaning in May 2025 had limited durability (re-submerged in August 2025 after 3 months).',
  options_considered: 3,
  recommended_option: mockInterventions[0],
  why_recommended: 'Mechanized High-Pressure Desilting provides the highest feasibility score (0.84), clears the critical bottleneck within 72 hours, fits current ward maintenance budget (₹85k vs ₹1.5L cap), and prevents immediate recurrence for the ongoing monsoon.',
  total_cost: 85000,
  timeline_days: 3,
  expected_outcome: '68% immediate risk reduction; drainage capacity restored to 100% of nominal 600mm design; zero standing water exceeding 10cm during standard rainfall events.',
  risks: [
    'Night work traffic disruption on FC Road between 23:00 and 05:00',
    'Re-sedimentation within 6-9 months if upstream hillside silt traps are not scheduled',
  ],
  assumptions: [
    'Vacuum suction tanker and high-pressure jetting units available in Ghole Road Ward Depot',
    'Cost calculation based on PMC PWD Schedule of Rates 2026 (SOR-2026/PW-412)',
  ],
  human_approval_required: true,
};

// ─── 10. Work Order & Execution ─────────────────────────────────────────────

export const mockWorkOrder: WorkOrder = {
  work_order_id: 'WO-2026-088',
  intervention_id: 'INT-001',
  case_id: 'CAS-PUN-2026-001',
  title: 'FC Road Corridor Mechanized Silt Extraction & Conduit Jetting',
  assigned_team: 'Ward 14 Emergency Drainage Rapid Response Unit',
  status: 'IN_PROGRESS',
  approval_state: 'APPROVED',
  created_at: '2026-10-03T09:30:00Z',
  approved_by: 'Executive Engineer V. K. Kulkarni (Drainage Dept)',
  approved_at: '2026-10-03T10:15:00Z',
  tasks: [
    {
      task_id: 'TSK-001',
      work_order_id: 'WO-2026-088',
      title: 'Traffic diversion coordination & safety zone cordoning',
      sequence: 1,
      status: 'COMPLETED',
      planned_duration_hours: 2,
      actual_duration_hours: 2.2,
      workers: ['Team Lead Jadhav', 'Traffic Warden Shinde', '2 Laborers'],
      equipment: ['safety_cones', 'warning_beacons', 'signboards'],
      planned_start: '2026-10-03T22:00:00Z',
      planned_end: '2026-10-04T00:00:00Z',
      actual_start: '2026-10-03T22:00:00Z',
      actual_end: '2026-10-04T00:12:00Z',
      notes: 'Coordinated with Shivajinagar Traffic Police Chowky. Southbound lane cordoned.',
    },
    {
      task_id: 'TSK-002',
      work_order_id: 'WO-2026-088',
      title: 'Heavy vacuum suction tanker positioning & deep chamber desilting',
      sequence: 2,
      status: 'IN_PROGRESS',
      planned_duration_hours: 4,
      actual_duration_hours: 3.5,
      workers: ['Tanker Operator Pawar', 'Helper Deshmukh', '2 Technicians'],
      equipment: ['vacuum_suction_tanker_MH12-PMC-4410', 'high_power_suction_hose'],
      materials: ['bio_neutralizer', 'sludge_containment_sacks'],
      planned_start: '2026-10-04T00:15:00Z',
      planned_end: '2026-10-04T04:15:00Z',
      actual_start: '2026-10-04T00:20:00Z',
      notes: 'Extracted 4.8 cubic meters of compacted silt from primary drop pit.',
    },
    {
      task_id: 'TSK-003',
      work_order_id: 'WO-2026-088',
      title: 'High-pressure water jetting through 120m conduit section',
      sequence: 3,
      status: 'PENDING',
      planned_duration_hours: 5,
      workers: ['Jetting Specialist More', '4 Crew Members'],
      equipment: ['high_pressure_jetting_rig_350bar', 'bullet_nozzle'],
      materials: ['water_tanker_supply_6000L'],
      dependencies: ['TSK-002'],
      planned_start: '2026-10-04T04:30:00Z',
      planned_end: '2026-10-04T09:30:00Z',
      notes: 'Scheduled to clear hard deposits between Goodluck Chowk and Fergusson College Gate.',
    },
    {
      task_id: 'TSK-004',
      work_order_id: 'WO-2026-088',
      title: 'Drop inlet grate replacement & acoustic flow test verification',
      sequence: 4,
      status: 'PENDING',
      planned_duration_hours: 3,
      workers: ['Quality Inspector Patil', '2 Fitters'],
      equipment: ['acoustic_flow_sensor', 'torque_wrench'],
      materials: ['ductile_iron_hinged_grates'],
      dependencies: ['TSK-003'],
      planned_start: '2026-10-04T10:00:00Z',
      planned_end: '2026-10-04T13:00:00Z',
      notes: 'Final physical inspection and evidence photograph capture.',
    },
  ],
};

// ─── 11. Field Verification ─────────────────────────────────────────────────

export const mockVerification: VerificationRecord = {
  verification_id: 'VER-2026-042',
  work_order_id: 'WO-2026-088',
  task_id: 'TSK-002',
  captured_at: '2026-10-04T03:45:12Z',
  latitude: 18.51862,
  longitude: 73.84153,
  image_url: '/images/verification_chamber_cleared.jpg',
  status: 'VERIFIED',
  overall_consistency: 'HIGH',
  checks: {
    gps_match: true,
    gps_deviation_meters: 3.4,
    timestamp_match: true,
    duplicate_check: false,
    visual_change_score: 0.92,
    notes: 'GPS geo-fence verified within 3.4m of Goodluck drop chamber. Optical telemetry confirms clear conduit aperture and complete evacuation of silt bed.',
  },
  action_taken: 'ACCEPT',
};

// ─── 12. Outcome & Prediction vs Reality ────────────────────────────────────

export const mockOutcome: Outcome = {
  outcome_id: 'OUT-PUN-2026-001',
  case_id: 'CAS-PUN-2026-001',
  observed_at: '2026-10-12T19:00:00Z',
  status: 'IMPROVED',
  prediction: {
    recurrence_probability: 0.18,
    expected_risk_reduction: 0.68,
  },
  observed: {
    recurrence: false,
    rainfall_event_date: '2026-10-12',
    rainfall_event_depth_mm: 42.4,
  },
  comparison: 'MATCHED',
  work_completed: true,
  problem_resolved: true,
  notes: 'Post-intervention comparable storm event (42.4mm rain in 90 mins). Street video and optical telemetry confirmed zero waterlogging depth above 5cm. Flow velocity through 600mm conduit reached 2.1 m/s without backflow.',
};

// ─── 13. Infrastructure Memory ──────────────────────────────────────────────

export const mockSiteMemory: InfrastructureMemory = {
  memory_id: 'MEM-PUN-SITE-001',
  site_id: 'SITE-PUN-001',
  site_label: 'FC Road Goodluck Chowk Corridor (Ward 14)',
  total_incidents: 4,
  recurring_count: 3,
  recurrence_interval_days: 88,
  past_interventions_count: 3,
  recurrence_after_intervention_count: 1,
  successful_outcomes_count: 2,
  cases: ['CAS-PUN-2024-019', 'CAS-PUN-2025-044', 'CAS-PUN-2026-001'],
  interventions: ['INT-2024-MANUAL', 'INT-2025-CLEARANCE', 'INT-2026-JETTING'],
  outcomes: ['OUT-2024-PARTIAL', 'OUT-2025-RECURRENCE', 'OUT-2026-MATCHED'],
  learned_patterns: [
    {
      pattern: 'Superficial manual desilting without high-pressure conduit jetting failed within 90 days due to rapid hill slope sediment accumulation.',
      durability_assessment: 'Limited durability (3 months)',
      advice: 'Always mandate mechanized vacuum suction + jetting when sediment depth exceeds 35% in Ward 14.',
    },
    {
      pattern: 'Rainfall events exceeding 28.5mm/hr reliably exceed surface drop inlet capacity in the Goodluck micro-basin.',
      durability_assessment: 'Permanent hydrologic constraint',
      advice: 'Long-term solution requires supplemental curb drop-inlets or conduit upsizing to 900mm prior to Monsoon 2027.',
    },
    {
      pattern: 'Coordinated night-time execution (22:00 to 05:00) reduced municipal traffic impact by 92% compared to daytime emergency pumping.',
      durability_assessment: 'High operational efficiency',
      advice: 'Institutionalize night shift protocol for all future FC Road drainage works.',
    },
  ],
};

// ─── 14. Cross-City Case Library ────────────────────────────────────────────

export const mockCrossCityCases: CrossCityCase[] = [
  {
    case_id: 'CC-AHM-01',
    city: 'Ahmedabad',
    corridor: 'Sabarmati Riverfront Arterial',
    problem_type: 'Micro-basin waterlogging with silted 750mm trunk',
    intervention: 'Mechanical vacuum suction + silt trap chamber retrofits',
    approx_cost_inr: 185000,
    reported_outcome: 'Zero waterlogging over 2 consecutive monsoon cycles',
    recurrence_observed: false,
    durability_months: 24,
    applicability_notes: 'High applicability to FC Road terrain. Adding an upstream silt catch-basin prevents recurrent conduit deposition.',
    source: 'Ahmedabad Municipal Corporation Engineering Report 2024',
    data_truth: 'REAL_DATA',
  },
  {
    case_id: 'CC-BLR-04',
    city: 'Bengaluru',
    corridor: 'Outer Ring Road (Bellandur Catchment)',
    problem_type: 'Sheet runoff ponding at localized roadway dip',
    intervention: 'Continuous precast slotted drain grating + regrading',
    approx_cost_inr: 320000,
    reported_outcome: 'Water clearing time reduced from 4 hours to 12 minutes',
    recurrence_observed: false,
    durability_months: 36,
    applicability_notes: 'Applicable as Option B alternative for Goodluck Chowk if localized camber regrading is approved.',
    source: 'BBMP Stormwater Directorate Technical Bulletin',
    data_truth: 'REAL_DATA',
  },
  {
    case_id: 'CC-CHE-09',
    city: 'Chennai',
    corridor: 'Velachery Main Road',
    problem_type: 'Culvert capacity bottleneck and outfall backflow',
    intervention: 'Trenchless micro-tunneling conduit expansion (600mm to 1000mm)',
    approx_cost_inr: 890000,
    reported_outcome: 'Permanent flood hazard reduction across 1.4km corridor',
    recurrence_observed: false,
    durability_months: 48,
    applicability_notes: 'Comparable to Option C. Capital intensive, recommended for multi-year capital budget inclusion.',
    source: 'Greater Chennai Corporation PWD Studies',
    data_truth: 'REAL_DATA',
  },
];
